//! Marigold is a domain specific language for data pipelining and analysis. It compiles to
//! asynchronous Rust and can be integrated into Rust programs using a macro.
//!
//! ## Example Usage
//!
//! ```rust
//! # #[tokio::main]
//! # async fn main() {
//! use marigold::m;
//! # use marigold::marigold_impl::StreamExt;
//!
//! let odd_digits = m!(
//!  fn is_odd(i: i32) -> bool {
//!    i.wrapping_rem(2) == 1
//!  }
//!
//!  range(0, 10)
//!    .filter(is_odd)
//!    .return
//! ).await.collect::<Vec<_>>().await;
//!
//! assert_eq!(odd_digits, vec![1, 3, 5, 7, 9]);
//! # }
//! ```
#![forbid(unsafe_code)]

pub use crate as marigold; // used so that the tests can reference re-exported values
pub use marigold_impl;

pub use marigold_macros::marigold as m;

/// OpenTelemetry instrumentation, available with the `otel` feature.
///
/// With the feature on, code generated by [`m!`](crate::m) records per-node metrics and spans to
/// the global OpenTelemetry providers. The `otel` feature brings only the OpenTelemetry API and
/// SDK, so it adds no HTTP client or async runtime and works with any executor; install a
/// provider of your own. The additional `otel-otlp` feature adds `telemetry::init`, which
/// exports over OTLP using the standard `OTEL_*` environment variables, with TLS for `https`
/// endpoints. Nothing is exported unless a provider is installed.
#[cfg(feature = "otel")]
pub mod telemetry {
    pub use marigold_impl::telemetry::*;
}
