[package]
name = "marigold-impl"
version = "0.1.8"
edition = "2021"
authors = ["Dominic <code@dominic.computer>"]
description = "Internal logic for the marigold language."
license = "Apache-2.0 OR MIT"
repository = "https://github.com/DominicBurkart/marigold"

[features]
default = ["tokio"]
tokio = ["dep:tokio"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.2"
futures = "0.3"
async-trait = "0.1.53"
binary-heap-plus = "0.4.1"
gen-nested-iter-yield = "=0.1.3"
genawaiter = {version = "0.99.1", features = ["futures03"]}
parking_lot = "0.12.0"
tokio = { version = "1", features = ["full", "tracing"], optional=true }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
