[package]
name = "marigold-impl"
version = "0.1.5"
edition = "2021"
authors = ["Dominic <code@dominic.computer>"]
description = "Internal logic for the marigold language."
license = "Apache-2.0 OR MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10.2"
futures = "0.3"
async-trait = "0.1.53"
binary-heap-plus = "0.4.1"
gen-nested-iter-yield = "0.1.0"

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
genawaiter = {version = "0.99.1", features = ["futures03"]}
