//! Pure-sync CSV row codec.
//!
//! This module is the *verified core* of Marigold's CSV IO. It handles
//! row-level encoding and decoding over a byte buffer with no async, no
//! allocations beyond `Vec`, and no external dependencies. The async IO
//! shell (`crate::writer`, and the code generated by
//! `marigold_grammar::pest_ast_builder` for `read_file`/`write_file`)
//! delegates per-row work here.
//!
//! The round-trip invariant `decode_row(encode_row(&r)) == Some(r.clone())`
//! is formally verified via Aeneas+Lean; see `dev_docs/aeneas/` at the
//! repository root. Do not change public signatures without updating the
//! corresponding Lean proofs. See `dev_docs/aeneas/agent_workflow.md`.

#![forbid(unsafe_code)]

/// A single CSV row: an ordered sequence of field byte strings.
///
/// Fields are arbitrary bytes; this MVP implementation handles an
/// RFC-4180 subset with no quoting and no embedded separators. See
/// `dev_docs/aeneas/invariants.md` for the precise guarantees.
#[derive(Debug, PartialEq, Eq, Clone)]
pub struct Row {
    pub fields: Vec<Vec<u8>>,
}

const FIELD_SEP: u8 = b',';
const ROW_TERM: u8 = b'\n';

/// Encode a row to bytes using an RFC-4180 subset: fields joined by
/// commas, terminated by LF. Field bytes MUST NOT contain `,` or `\n`;
/// passing such a row produces output that cannot be round-tripped.
///
/// See `dev_docs/aeneas/invariants.md` for the formal round-trip claim.
pub fn encode_row(row: &Row) -> Vec<u8> {
    let mut out: Vec<u8> = Vec::new();
    let n = row.fields.len();
    let mut i = 0usize;
    while i < n {
        let field = &row.fields[i];
        let mut j = 0usize;
        while j < field.len() {
            out.push(field[j]);
            j += 1;
        }
        if i + 1 < n {
            out.push(FIELD_SEP);
        }
        i += 1;
    }
    out.push(ROW_TERM);
    out
}

/// Decode a single row from bytes. Returns `None` if the byte slice is
/// not a well-formed encoding produced by `encode_row`.
///
/// Well-formed = non-empty, terminated by a single LF, with no LF bytes
/// preceding the terminator. Empty input returns `None`. A slice
/// consisting solely of `\n` decodes to `Row { fields: vec![vec![]] }`.
pub fn decode_row(bytes: &[u8]) -> Option<Row> {
    if bytes.is_empty() {
        return None;
    }
    // Terminator must be the final byte, and the only LF.
    let last = bytes.len() - 1;
    if bytes[last] != ROW_TERM {
        return None;
    }
    // Reject any LF before the terminator.
    let mut k = 0usize;
    while k < last {
        if bytes[k] == ROW_TERM {
            return None;
        }
        k += 1;
    }
    // Split on FIELD_SEP.
    let mut fields: Vec<Vec<u8>> = Vec::new();
    let mut current: Vec<u8> = Vec::new();
    let mut i = 0usize;
    while i < last {
        let b = bytes[i];
        if b == FIELD_SEP {
            fields.push(current);
            current = Vec::new();
        } else {
            current.push(b);
        }
        i += 1;
    }
    fields.push(current);
    Some(Row { fields })
}

#[cfg(test)]
mod tests {
    use super::*;
    use proptest::prelude::*;

    // Strategy: generate a Row with 1..=8 fields, each field a Vec<u8>
    // of length 0..=16 containing bytes that are NOT `,` or `\n`.
    fn arb_row() -> impl Strategy<Value = Row> {
        prop::collection::vec(
            prop::collection::vec(
                any::<u8>().prop_filter("no sep or lf", |b| *b != FIELD_SEP && *b != ROW_TERM),
                0..=16,
            ),
            1..=8,
        )
        .prop_map(|fields| Row { fields })
    }

    #[test]
    fn encode_empty_field_single() {
        let r = Row {
            fields: vec![vec![]],
        };
        let enc = encode_row(&r);
        assert_eq!(enc, b"\n");
        assert_eq!(decode_row(&enc), Some(r));
    }

    #[test]
    fn encode_single_field() {
        let r = Row {
            fields: vec![b"hello".to_vec()],
        };
        let enc = encode_row(&r);
        assert_eq!(enc, b"hello\n");
        assert_eq!(decode_row(&enc), Some(r));
    }

    #[test]
    fn encode_multi_field() {
        let r = Row {
            fields: vec![b"a".to_vec(), b"bc".to_vec(), b"".to_vec()],
        };
        let enc = encode_row(&r);
        assert_eq!(enc, b"a,bc,\n");
        assert_eq!(decode_row(&enc), Some(r));
    }

    #[test]
    fn decode_empty_returns_none() {
        assert_eq!(decode_row(b""), None);
    }

    #[test]
    fn decode_missing_terminator_returns_none() {
        assert_eq!(decode_row(b"abc"), None);
    }

    #[test]
    fn decode_internal_lf_returns_none() {
        assert_eq!(decode_row(b"a\nb\n"), None);
    }

    proptest! {
        #[test]
        fn roundtrip(r in arb_row()) {
            let encoded = encode_row(&r);
            let decoded = decode_row(&encoded);
            prop_assert_eq!(decoded, Some(r));
        }

        #[test]
        fn encoded_length_predictable(r in arb_row()) {
            let encoded = encode_row(&r);
            let n = r.fields.len();
            let sum_field_lens: usize = r.fields.iter().map(|f| f.len()).sum();
            // sum + (n-1) separators + 1 terminator
            let expected = sum_field_lens + n.saturating_sub(1) + 1;
            prop_assert_eq!(encoded.len(), expected);
        }
    }
}
