name:                actions

on:                  [push]

env:
  CARGO_TERM_COLOR:  always

jobs:
  pre-commit:
    runs-on:         ubuntu-latest
    steps:
    - uses:          actions/checkout@v2
    - uses:          actions/setup-python@v2
    - uses:          actions-rs/toolchain@v1
      with:
          toolchain: stable
    - uses:          pre-commit/action@v2.0.3
  test:
    runs-on:         ubuntu-latest
    steps:
    - uses:          actions/checkout@v2
    - uses:          actions-rs/toolchain@v1
      with:
          toolchain: stable
    - run:           cargo test
  linux_x86:
    name:            Linux x86 Build
    runs-on:         ubuntu-latest
    steps:
      - uses:        actions/checkout@v2
      - uses:        actions-rs/toolchain@v1
        with:
          toolchain: stable
          target:    x86_64-unknown-linux-gnu
          override:  true
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target x86_64-unknown-linux-gnu
  linux_aarch64:
    name:            Aarch64 Build
    runs-on:         ubuntu-latest
    steps:
      - uses:        actions/checkout@v2
      - uses:        actions-rs/toolchain@v1
        with:
          toolchain: stable
          target:    aarch64-unknown-linux-gnu
          override:  true
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target aarch64-unknown-linux-gnu
  linux_arm7:
    name:            Linux ARMv7 Build
    runs-on:         ubuntu-latest
    steps:
      - uses:        actions/checkout@v2
      - uses:        actions-rs/toolchain@v1
        with:
          toolchain: stable
          target:    armv7-unknown-linux-gnueabihf
          override:  true
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target armv7-unknown-linux-gnueabihf
  mac_x86:
    name:            Mac x86_64 Build
    runs-on:         ubuntu-latest
    steps:
      - uses:        actions/checkout@v2
      - uses:        actions-rs/toolchain@v1
        with:
          toolchain: stable
          target:    x86_64-apple-darwin
          override:  true
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target x86_64-apple-darwin
  windows_x86:
    name:            Windows x86_64 Build
    runs-on:         ubuntu-latest
    steps:
      - uses:        actions/checkout@v2
      - uses:        actions-rs/toolchain@v1
        with:
          toolchain: stable
          target:    x86_64-pc-windows-gnu
          override:  true
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target x86_64-pc-windows-gnu
