name:                arm7

on:                  [push]

env:
  CARGO_TERM_COLOR:  always

jobs:
  linux_arm7:
    name:            Linux ARMv7 Build
    runs-on:         ubuntu-latest
    steps:
      - uses:        actions/checkout@v3
      - uses:        actions-rs/toolchain@v1
        with:
          toolchain: stable
          target:    armv7-unknown-linux-gnueabihf
          override:  true
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target armv7-unknown-linux-gnueabihf
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target armv7-unknown-linux-gnueabihf --features tokio,io
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target armv7-unknown-linux-gnueabihf --features tokio
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target armv7-unknown-linux-gnueabihf --features async-std
