name:               badges

on:                 [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  lines_of_code:
    runs-on:        ubuntu-latest
    steps:
      - uses:       actions/checkout@v3
      - name:       "Make lines of code badge"
        run:        |
          rm -f .github/badges/lines_of_code.svg .github/badges/lines_of_code_ftb.svg || true
          curl "https://img.shields.io/badge/lines%20of%20code-$(git ls-files | grep -e '\.rs' -e '\.lalrpop' | xargs wc -l | tail -n 1 | awk '{$1=$1};1' | cut -d " " -f1)-informational" >> .github/badges/lines_of_code.svg
          curl "https://img.shields.io/badge/lines%20of%20code-$(git ls-files | grep -e '\.rs' -e '\.lalrpop' | xargs wc -l | tail -n 1 | awk '{$1=$1};1' | cut -d " " -f1)-informational?style=for-the-badge" >> .github/badges/lines_of_code_ftb.svg
          git config user.name dominicburkart
          git config user.email code@dominic.computer
          git add .github/badges/lines_of_code.svg .github/badges/lines_of_code_ftb.svg
          git commit -m "update lines of code badge" || true
          git push || true
