name:                bench

on:                  [push]

env:
  CARGO_TERM_COLOR:  always

jobs:
  test:
    name:            Benches
    runs-on:         ubuntu-latest
    steps:
    - uses:          actions/checkout@v3
    - uses:          actions-rs/toolchain@v1
      with:
          toolchain: stable
    - run:           cargo bench
