name:                mac_x86

on:                  [push]

env:
  CARGO_TERM_COLOR:  always

jobs:
  mac_x86:
    name:            Mac x86_64 Build
    runs-on:         macos-latest
    steps:
      - uses:        actions/checkout@v2
      - uses:        actions-rs/toolchain@v1
        with:
          toolchain: stable
          target:    x86_64-apple-darwin
          override:  true
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target x86_64-apple-darwin
