name:                mac_x86

on:                  [push]

env:
  CARGO_TERM_COLOR:  always

jobs:
  mac_x86:
    name:            Mac x86_64 Build
    runs-on:         macos-latest
    steps:
      - uses:        actions/checkout@v2
      - uses:        actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run:         cargo build
      - run:         cargo build --features tokio,io
      - run:         cargo build --features tokio
      - run:         cargo build --features async-std
