name: onboarding

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  onboarding:
    name: Onboarding
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: shellcheck install.sh install_test.sh
    - run: sh install_test.sh
    - run: cargo install --path marigold -F cli
    - run: marigold run hello_world.marigold
    - run: marigold analyze hello_world.marigold
