name:                Pre-Commit Hooks

on:
  push:
    branches:        main
  pull_request:
    branches:        [ main ]

env:
  CARGO_TERM_COLOR:  always

jobs:
  pre-commit:
    name:            Pre-commit Hooks
    runs-on:         ubuntu-latest
    steps:
    - uses:          actions/checkout@v2
    - uses:          actions/setup-python@v2
    - uses:          actions-rs/toolchain@v1
      with:
          toolchain: stable
    - uses:          pre-commit/action@v2.0.3
