name:                style

on:                  [push]

env:
  CARGO_TERM_COLOR:  always

jobs:
  pre-commit:
    name:            style hooks
    runs-on:         ubuntu-latest
    steps:
    - uses:          actions/checkout@v2
    - uses:          actions/setup-python@v2
    - uses:          actions-rs/toolchain@v1
      with:
          toolchain: stable
    - uses:          pre-commit/action@v2.0.3
