name:                tests

on:                  [push, pull_request]

env:
  CARGO_TERM_COLOR:  always

jobs:
  test:
    name:            Tests
    runs-on:         ubuntu-latest
    steps:
    - uses:          actions/checkout@v2
    - uses:          actions-rs/toolchain@v1
      with:
          toolchain: stable
    - run:           cargo test
    - run:           cargo test --features tokio,io
    - run:           cargo test --features tokio
    - run:           cargo test --features async-std
    - run:           cargo test --all-features

  coverage:
    name:            Coverage
    runs-on:         ubuntu-latest
    environment:     codecov
    steps:
    - uses:          actions/checkout@v4
    - uses:          dtolnay/rust-toolchain@stable
    - name:          Install cargo-tarpaulin
      run:           cargo install cargo-tarpaulin
    - name:          Generate coverage
      run:           cargo tarpaulin --all-features --ignore-tests --workspace --exclude color-palette-picker --exclude csv --exclude multi-consumer --exclude select-all --exclude stateful --exclude bounded-types --out Lcov --output-dir .
    - name:          Upload coverage reports
      uses:          codecov/codecov-action@v5
      with:
        token:       ${{ secrets.CODECOV_TOKEN }}
        files:       lcov.info
        fail_ci_if_error: true
