name:                tests

on:                  [push]

env:
  CARGO_TERM_COLOR:  always

jobs:
  test:
    name:            Tests
    runs-on:         ubuntu-latest
    steps:
    - uses:          actions/checkout@v2
    - uses:          actions-rs/toolchain@v1
      with:
          toolchain: stable
    - run:           cargo test
