name:                x86

on:                  [push]

env:
  CARGO_TERM_COLOR:  always

jobs:
  linux_x86:
    name:            Linux x86 Build
    runs-on:         ubuntu-latest
    steps:
      - uses:        actions/checkout@v3
      - uses:        actions-rs/toolchain@v1
        with:
          toolchain: stable
          target:    x86_64-unknown-linux-gnu
          override:  true
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target x86_64-unknown-linux-gnu
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target x86_64-unknown-linux-gnu --features tokio,io
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target x86_64-unknown-linux-gnu --features tokio
      - uses:        actions-rs/cargo@v1
        with:
          use-cross: true
          command:   build
          args:      --target x86_64-unknown-linux-gnu --features async-std
